apiVersion: v1
kind: PersistentVolume
metadata:
  name: prueba-mysql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /tmp
    server: 172.17.0.2
  # persistentVolumeReclaimPolicy: Delete
  # storageClassName: ibmc-vpc-block-general-purpose
  volumeMode: Filesystem
  claimRef:
    namespace: prueba-mysql
    name: mysql