apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql
    namespace: prueba-mysql
  nfs:
    server: 172.17.0.2
    path: /var/lib/mysql/data
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem