apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql
    namespace: prueba-mysql
  hostPath:
    path: /mnt/pv-data/pv-mysql
    type: ""
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem